# Generated by Django 4.1.4 on 2022-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categoryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
